// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5ib9FZEPbDuAxynXNaGRP8u-7swGVzw',
    appId: '1:234611875811:web:ba892450713d37ee5ecad6',
    messagingSenderId: '234611875811',
    projectId: 'social-9a78a',
    authDomain: 'social-9a78a.firebaseapp.com',
    storageBucket: 'social-9a78a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIBrQjWSUhuKW6upR8sai0GmW_gFw2a0',
    appId: '1:234611875811:android:24645eb966edbe4e5ecad6',
    messagingSenderId: '234611875811',
    projectId: 'social-9a78a',
    storageBucket: 'social-9a78a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZxPNM-4tIwIdh6eQB7VF3F-MKkE61RR8',
    appId: '1:234611875811:ios:746da27d8d0b8abe5ecad6',
    messagingSenderId: '234611875811',
    projectId: 'social-9a78a',
    storageBucket: 'social-9a78a.appspot.com',
    iosClientId: '234611875811-vrbagkeeu1uk8e357b8njhf7mc0btit8.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZxPNM-4tIwIdh6eQB7VF3F-MKkE61RR8',
    appId: '1:234611875811:ios:c97838db286911815ecad6',
    messagingSenderId: '234611875811',
    projectId: 'social-9a78a',
    storageBucket: 'social-9a78a.appspot.com',
    iosClientId: '234611875811-k15f3qcdkod254n1h822rs7q06jcc1aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.social.RunnerTests',
  );
}
